### PR TITLE
fixes issue #681 with pasteHtml incorrectly re-hydrating tabs.

### LINKED ISSUE #681: pasteHTML (pasting html generated by Quill) is stripping out ql-indent classes
Calling pasteHTML with quill generated html that has indented bits (ie. `<p class="ql-indent-1">...`) strips off the ql-indent-1 class name in the editor and removes the indent.  This happens with nested lists too.

**Steps for Reproduction**

1. Visit http://codepen.io/jonnolen/pen/GZaaaX
2. Enter text into left hand quill editor that is indented.
3. Press "Paste It!" button, (it calls pasteHTML with a copy of the html that has been stashed in a hidden div.)

**Expected behavior**: Indents are preserved in the editor.

**Actual behavior**: Indents are stripped.

**Platforms**: Chrome  50.0.2661.94 (64-bit) on Mac OS 10.11.4

**Version**: 1.0.0-beta.2-5aa302

### PR DESCRIPTION
**Pull request by jonnolen**
Resolves #681 

Current version of quill 1.0 beta demonstrating problem: http://codepen.io/jonnolen/pen/GZaaaX

Version of quill 1.0 beta built with changes demonstrating problem resolved: http://codepen.io/jonnolen/pen/XdLaGO

### CODE REVIEW

**Comment by jhchen** [comment]
Thanks for the PR. The string vs number difference is indeed the root issue but I'd prefer if we went the other direction in converting to number so numeric comparisons can still be used. Can you update the PR to do this instead? I think just adding a custom value() function should work.

**Comment by jonnolen** [comment]
@jhchen please check it now.

**Comment by jonnolen** [comment]
Bleargh.  there is a coercion problem in the toolbar module, updating that now.

File: formats/indent.js [hunk 1]
```diff
@@ -3,8 +3,8 @@ import Parchment from 'parchment';
 class IdentAttributor extends Parchment.Attributor.Class {
   add(node, value) {
     if (value === '+1' || value === '-1') {
```
Comment (jonnolen) [inline formats/indent.js]: I actually think this can and should be removed... the +1/-1 is really a function of the toolbar and is handled as such in modules/toolbar.js, with the debugger attached, this method never got hit with a value that was a string === "+1" || "-1" it was always the existing indent incremented or decremented.

File: modules/toolbar.js [hunk 2]
```diff
@@ -107,7 +107,7 @@ class Toolbar extends Module {
           option.selected = true;
         }
       } if (input.value) {
-        input.classList.toggle('ql-active', input.value == formats[format]);  // Intentional ==
+        input.classList.toggle('ql-active', input.value === formats[format]);
```
Comment (jonnolen) [inline modules/toolbar.js]: since this change allows a white list to be specified as integers instead of strings but the value "+1" actually matters for indent toolbar buttons, it needs to be ===.  

The way it was, an active button can't be clicked twice and the button is determined active if the value of the button is the same as the value of the format. An active button can't be activated again and the value for the button was being set to `false` before being passed through to format. 

The root cause is that == will coerce a string to an integer to do a comparison, which in the case of indent means a delta with format `'indent': 1` has the same value as `"+1"`, which is not really true for the `indent "+1"` button.

I think this change isn't necessary if the restriction that whitelists be strings and and Attributor.value always returns a string is in place.  If we allow the whitelist to contain numbers, then the attributor with a numeric whitelist's value function needs to return a number.  If value can return a number instead of string then toolbar update needs strict ===.

File: formats/indent.js (hunk 1 above)
Comment (jhchen) [inline formats/indent.js]: The keyboard also uses this +1/-1 functionality

File: modules/toolbar.js (hunk 2 above)
Comment (jhchen) [inline modules/toolbar.js]: I believe the general case of <button value="1"> gets broken by this === change.

**Comment by jhchen** [comment]
I'll merge this to avoid the back and forth but I'm probably going to change the === back as I think it will cause a regression.

File: modules/toolbar.js (hunk 2 above)
Comment (jonnolen) [inline modules/toolbar.js]: i don't think it does... but i'll test in the code pen.

**Comment by jonnolen** [comment]
the === being set to == breaks the +1 button

**Comment by jhchen** [comment]
I guess I should have said that I will not be keeping === rather than I will be changing it back.
